name: CD - Deploy to Google Cloud VM (Staging Only)

on:
  push:
    branches: [ main, master, develop ]
  workflow_dispatch:

env:
  DOCKER_IMAGE: joomla-app
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  ZONE: ${{ secrets.GCP_ZONE }}

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Joomla Docker image
      run: |
        docker build -t ${{ env.DOCKER_IMAGE }}:${{ github.sha }} .
        docker save ${{ env.DOCKER_IMAGE }}:${{ github.sha }} > joomla-image.tar

    - name: Create deployment package
      run: |
        # Create deployment directory
        mkdir -p deployment
        
        # Copy necessary files
        cp joomla-image.tar deployment/
        cp docker-compose.prod.yml deployment/docker-compose.yml
        cp deploy/scripts/deploy.sh deployment/
        cp deploy/scripts/setup-vm.sh deployment/
        
        # Create deployment archive
        tar -czf deployment-package.tar.gz deployment/

    - name: Upload deployment artifact
      uses: actions/upload-artifact@v4
      with:
        name: deployment-package
        path: deployment-package.tar.gz
        retention-days: 30

  deploy:
    name: Deploy to Google Cloud VM
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: http://${{ steps.get-ip.outputs.vm-ip }}
    
    steps:
    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Ensure VM exists and get IP
      id: get-ip
      run: |
        # Check if VM exists, create if it doesn't
        if ! gcloud compute instances describe joomla-server --zone=${{ env.ZONE }} >/dev/null 2>&1; then
          echo "VM joomla-server not found. Creating it..."
          gcloud compute instances create joomla-server \
            --zone=${{ env.ZONE }} \
            --machine-type=f1-micro \
            --network-tier=PREMIUM \
            --subnet=default \
            --maintenance-policy=MIGRATE \
            --tags=http-server,https-server \
            --image=ubuntu-2004-focal-v20231213 \
            --image-project=ubuntu-os-cloud \
            --boot-disk-size=30GB \
            --boot-disk-type=pd-standard
          
          echo "VM created. Waiting for it to be ready..."
          sleep 60
          
          # Run setup script on new VM
          gcloud compute ssh joomla-server --zone=${{ env.ZONE }} --command="
            sudo apt update && \
            curl -fsSL https://get.docker.com -o get-docker.sh && \
            sudo sh get-docker.sh && \
            sudo usermod -aG docker \$USER && \
            sudo mkdir -p /opt/joomla && \
            sudo chown -R \$USER:\$USER /opt/joomla
          "
        fi
        
        # Get VM IP
        VM_IP=$(gcloud compute instances describe joomla-server \
          --zone=${{ env.ZONE }} \
          --format="get(networkInterfaces[0].accessConfigs[0].natIP)")
        echo "vm-ip=$VM_IP" >> $GITHUB_OUTPUT
        echo "VM IP: $VM_IP"

    - name: Download deployment artifact
      uses: actions/download-artifact@v4
      with:
        name: deployment-package

    - name: Deploy to VM
      env:
        VM_IP: ${{ steps.get-ip.outputs.vm-ip }}
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      run: |
        # Setup SSH using gcloud
        gcloud compute config-ssh

        # Copy deployment package to VM
        gcloud compute scp deployment-package.tar.gz joomla-server:/tmp/ --zone=${{ env.ZONE }}

        # Deploy on VM
        gcloud compute ssh joomla-server --zone=${{ env.ZONE }} --command="
          set -e
          
          # Extract deployment package
          cd /tmp
          tar -xzf deployment-package.tar.gz
          cd deployment
          
          # Make scripts executable
          chmod +x deploy.sh setup-vm.sh
          
          # Run deployment script
          sudo ./deploy.sh staging \
            '${{ env.MYSQL_ROOT_PASSWORD }}' \
            '${{ env.MYSQL_DATABASE }}' \
            '${{ env.MYSQL_USER }}' \
            '${{ env.MYSQL_PASSWORD }}' \
            '${{ github.sha }}'
          
          echo 'Deployment completed successfully'
        "

  notify:
    name: Notify Deployment
    needs: [deploy]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Notify success
      if: needs.deploy.result == 'success'
      run: |
        echo "🎉 Google Cloud VM deployment successful!"
        echo "📍 Staging URL: http://${{ needs.deploy.outputs.vm-ip || 'Check logs for IP' }}"
        echo "🔧 Access your Joomla site and complete the installation wizard"
        
    - name: Notify failure
      if: needs.deploy.result == 'failure'
      run: |
        echo "❌ Google Cloud VM deployment failed!"
        echo "🔍 Check the workflow logs for details"